---
name: setup
description: set up the stage for building and testing
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
        cache: true
        check-latest: true
    - uses: ko-build/setup-ko@v0.9
