---
version: "2"
linters:
  enable:
    - gosec
    - revive
    - misspell
    - gocritic
  disable:
    - errcheck

  exclusions:
    rules:
    - path: \.go$
      text: "should have a package comment"
      linters:
      - revive
    - path: pkg/shp/cmd/(build|version)/
      text: "var-naming: avoid package names that conflict with Go standard library package names"
      linters:
      - revive
