---
name: Unit Tests

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: make test-unit

  test-unit-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
          cache: true
          check-latest: true

      - name: Run Unit Tests
        run: go test -mod=vendor -race -cover ./cmd/shp/... ./pkg/...
